-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le : Mer 16 Octobre 2013 à 16:22
-- Version du serveur: 5.5.16
-- Version de PHP: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `mysocialmatch`
--

-- --------------------------------------------------------

--
-- Structure de la table `description`
--

CREATE TABLE IF NOT EXISTS `description` (
  `id_description` int(11) NOT NULL AUTO_INCREMENT,
  `description` text NOT NULL,
  PRIMARY KEY (`id_description`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=157 ;

--
-- Contenu de la table `description`
--

INSERT INTO `description` (`id_description`, `description`) VALUES
(1, 'Bélier et Gémeaux s''entraînent l''un l''autre avec bonheur sur les chemins de l''existence. Tous deux enthousiastes et heureux de vivre, ils se sentent stimulés par leur partenaire qui leur permet de réaliser leurs rêves les plus fous. Attention toutefois, ce couple devra se projeter sur le long terme afin de construire une histoire solide et ne pas profiter uniquement du moment présent.'),
(2, 'Quelle jolie fusion que celle d''un Bélier et Sagittaire ! Ces deux signes ont tout pour s''entendre : ils partagent la même vision de la vie, optimiste et joyeuse, et ont tous les deux envie de la croquer à pleines dents. Ils peuvent ainsi évoluer dans la joie et la bonne humeur, avec le sentiment précieux d''avoir trouvé la personne avec qui partager leur existence.'),
(3, 'Deux Taureaux réunis font en général des merveilles sur la durée. Ils partagent les mêmes qualités, pragmatisme, organisation, logique, et aiment élaborer des projets de vie en commun.  Par ailleurs ils se comprennent l''un l''autre au premier coup d''oeil. Leur entente est en général excellente.'),
(4, 'Le Cancer et le Taureau sont faits pour s''entendre, aussi bien d''un point de vue affectif que professionnel. Ils ont tous deux les pieds sur terre et partagent les mêmes valeurs de vie. Socialement, ils privilégient le confort et la sécurité du foyer aux mondanités. Professionnellement, ce sont de durs travailleurs, rigoureux et logiques. Leur alliance est vouée au succès.'),
(5, 'Le Taureau et la Vierge ensemble forment en général une alliance paisible et épanouie. Ces deux signes sont calmes et réfléchis, pragmatiques et posés. Ils aiment les mêmes choses et partagent une conception identique de l''existence. La Vierge, anxieuse de nature, est rassurée par le côté solide de son partenaire tandis que ce dernier apprécie les qualités de coeur et la sensibilité de la Vierge.'),
(6, 'Le Taureau et le Capricorne forment en général une alliance des plus réussies. Ces deux signes se comprennent à merveille au niveau de leur conception de l''existence, solide, pragmatique, travailleuse. Ils sont prêts à donner beaucoup à leur partenaire et à travailler d''arrache pied afin d''atteindre leurs objectifs. '),
(7, 'Cette alliance fait des étincelles ! Les qualités similaires de deux Gémeaux ensemble ne s''ajoutent pas, elles se démultiplient. Ayant pleinement conscience d''avoir trouvé un partenaire à la hauteur de leur vision de la vie, ils le choient et le couvrent d''attention. Voilà une alliance qui a toutes les chances de réussir !'),
(8, 'Une association intelligente et ambitieuse, qui ne manque pas de piment ni de brillant ! Ils se complètent parfaitement pour accomplir de grands desseins. Un p’tit air de supériorité en duo, une sacrée prestance et une étonnante complémentarité.'),
(9, 'Le Gémeaux et a Balance sont deux signes d''Air et s’entendent parfaitement. Ils partagent la même vision de l''existence dégagée au maximum des contraintes, le même enthousiasme et la même légèreté. Ensemble, la vie leur semble une fête sans fin, ce qu''ils apprécient énormément.'),
(10, 'Quelle alchimie que celle d''un Gémeaux et d''un Verseau ensemble ! Ces deux signes sont faits pour se rencontrer et pour être heureux ensemble. Ils partagent la même vision de la vie, éprise de liberté et d''aventure, la même ouverture sociale et le même enthousiasme en général. Que demander de plus ? Le Gémeaux et le Verseau n''ont même pas besoin de se parler pour se comprendre.'),
(11, 'Deux Cancers sont faits pour s''entendre, et leur association a toutes les chances de fonctionner sur la durée. Ils partagent les mêmes valeurs et la même vision de la vie, ancrée dans la réalité. Ils aiment les mêmes choses, la sécurité d''un foyer, l''établissement d''une famille, et sont tous deux prêts à s''investir totalement dans leur relation.'),
(12, 'Le Cancer et le Scorpion ont une passion commune : l’émotion ! Voilà une association mouvante et passionnée, souvent sans queue ni tête mais qui vous laissera le coeur sens dessus dessous ! Sur la même longueur d’onde, ces deux signes fusionnent  et se font réellement vibrer.'),
(13, 'Le Cancer et le Poisson sont faits pour s''entendre. Ces deux signes d''Eau partagent la même vision rêveuse de la vie, les mêmes aspirations et la même sensibilité à fleur de peau. En conséquence, ils comprennent parfaitement les sautes d''humeur de leur partenaire et leur pardonnent leurs angoisses, cherchant en premier lieu à les rassurer. Ils forment ainsi une très belle alliance.'),
(14, 'Quelle aventure que deux lions réunis ! Deux charismes, deux personnalités qui s’attirent ! Ce couple voit les choses en grand, leur association est tout aussi passionnée que féroce.'),
(15, 'Quelle magnifique alliance que celle d''un Lion et d''un Sagittaire ! De fait, ces deux signes de Feu font des étincelles lorsqu''ils sont réunis, rien de moins. Ils partagent la même vision de l''existence et sont prêts à s''investir corps et âme dans une relation lorsqu''ils estiment qu''elle en vaut la peine. Leurs qualités immenses se rejoignent et se complètent à merveille, faisant de ce duo un des couples les plus réussis du zodiaque.'),
(16, 'Deux vierges ensemble donnera une association très sensée. Ce duo mettra très vite de côté le côté grain de folie du couple pour mieux se rattraper sur la communauté d’intérêts. C’est un couple qui sait garder la tête froid et gérer toutes les préoccupations de la vie. L’amour est pour eux un long fleuve tranquille.'),
(17, 'Vierge et Capricorne bénéficient en général, et ce, dès leur première rencontre, d''une excellente entente intellectuelle. Ils se retrouvent en effet autour des mêmes valeurs de vie. Comme on dit souvent, qui se ressemble s’assemble !'),
(18, 'Ce duo aime les sensations fortes, les vertiges, et la passion. Deux Scorpions ensemble, voilà une association qui n''est pas de tout repos, loin de là ! Cette union promet autant de rebondissements que de confrontations. '),
(19, 'L’union entre ces deux signes peut être complexe, mais le Capricorne étant plutôt terre à terre apportera une certaine stabilité dans le couple. Ce qu''il faudra donc à ce couple c''est de savoir communiquer pour éviter les tensions. '),
(20, 'Il existe en général une très bonne alchimie entre le Scorpion et le Poisson , même si ces deux caractères sont à l''origine très dissemblables. Mais à partir du moment où le Poissons accepte son partenaire tel qu''il est, avec ses qualités et ses défauts, ce dernier s''adoucit et offre à son compagnon les richesses insoupçonnées de son coeur. A ce moment, cette relation peut s''épanouir pleinement, et ce sur le long terme.'),
(21, 'Quel enthousiasme et quel dynamisme lorsque deux Sagittaire sont ensemble ! Pas de doute, ces deux êtres étaient faits pour se rencontrer. Leur joie de vivre instinctive, leur envie de foncer à l''aventure, est décuplée lorsqu''ils rencontrent un partenaire du même signe. Ils en sont ravis et ont en général conscience de la chance qu''ils ont.'),
(22, 'Il y a un aspect très joyeux dans le couple formé par un Sagittaire et un Verseau. Ces deux signes partagent une vision de l''existence similaire basée sur l''optimisme, la soif d''aventure et la liberté. Que demander de plus ? Ils s''accordent à merveille et sont en général très heureux d''avoir rencontré un compagnon qui partage ces qualités avec eux.'),
(23, 'L''association entre deux Capricorne est excellente sur le plan professionnel. Ce sont d''infatigables travailleurs, pragmatiques et matérialistes. L''association est cependant moins pérenne d''un point de vue affectif. Leur relation risque en effet de singulièrement manquer de gaieté et d''allant, les Capricorne étant par nature taciturnes et pessimistes. Il leur manquera la complémentarité d''un partenaire plus joyeux.'),
(24, 'L''association entre deux Verseaux est en général pour le moins originale. Les deux partenaires ayant une vision pareillement anticonformiste de l''existence. Leur alliance les mène souvent à développer un mode de vie qui leur est très personnel, et leur convient à merveille. Déconnectés de la réalité, ils peuvent rêver ensemble d''un avenir et s''épanouir parfaitement dans leur bulle.'),
(25, 'La fierté et l''orgueil sont deux caractéristiques propres aussi bien au Bélier qu''au Lion. Pas facile donc d''allier ces deux signes sans qu''un des deux partenaires ne se sente lésé. Chacun voudra constamment prendre le dessus ! En revanche s''ils arrivent à trouver un équilibre, cette relation sera destinée à durer et à faire des étincelles, le Lion et le Bélier se tirant mutuellement vers le haut.'),
(26, 'Il est connu que les opposés s''attirent, et l''alliance entre un Scorpion et un Taureau en est le parfait exemple. Le Taureau, pragmatique et terre à terre, est fasciné par la complexité angoissée du Scorpion, ainsi que par son côté obscur. De son côté, celui-ci trouve enfin dans son alliance avec le Taureau une épaule solide sur laquelle s''appuyer, et un socle pour la construction d''une vie de couple épanouie.'),
(27, 'Il peut exister une réelle complémentarité entre un Poissons et un Taureau. Le premier saura en effet apprécier à sa juste valeur les qualités du Taureau, son pragmatisme, son sens des réalités, sa solidité affective. Tandis que le second sera fasciné par l''imagination, la finesse et l''univers propres au Poissons. Entre les deux existera un véritable intérêt mutuel et un respect qui leur permettront d''évoluer sereinement dans leur relation.'),
(28, 'L''association entre un Gémeaux et une Vierge est à la fois complexe et intéressante. A première vue ces caractères ont peu en commun, le côté organisé et rigoureux de la Vierge s''accorde mal aux débordements du Gémeaux,  et pourtant ils se complètent souvent très bien, chacun admirant chez l''autre ses spécificités, ce qui en fait une relation des plus réussies.'),
(29, ' Le Gémeaux et le Sagittaire sont faits pour s''entendre d''un point de vue social et mondain. En effet, pour ces deux signes c''est une composante essentielle de l''existence que d''être entourés et de rencontrer de nouvelles têtes. Par ailleurs, ils partageront une même légèreté un peu superficielle qui leur conviendra à merveille, et un optimisme des plus agréables.'),
(30, 'L''alliance d''un Cancer et d''un Lion peut sembler à première vue improbable, et pourtant elle est en général vouée à la réussite. Ces deux signes se complètent à merveille, le Lion adorant prendre la première place et le Cancer étant plus à l''aise dans l''ombre. L''affection sincère du Lion rassurera son partenaire, tandis que ce dernier admirera sans limites le Lion. Que demander de plus ?'),
(31, 'Le Cancer et le Capricorne s''entendent en général à merveille, que ce soit d''un point de vue affectif ou professionnel. Ces deux signes se complètent très bien car ils partagent le même besoin de stabilité et de sécurité. Ils formeront donc une alliance efficace et respectueuse qui leur permettra de construire de nombreuses choses ensemble.'),
(32, 'L''association entre une Vierge et un Lion réunit a priori toutes les conditions pour fonctionner à merveille. La Vierge laisse avec plaisir la place d''honneur au Lion, et ce dernier apprécie pleinement les grandes qualités de coeur de sa partenaire.'),
(33, 'Harmonie est le maître mot d''une relation entre deux Balance. En effet, ces deux êtres partagent la même vision de la vie, optimiste et légère. Ils sont ravis de rencontrer un partenaire qui les comprenne et partagent la même vision de l''existence. Et il n''y a pas de risque de brouille, les deux détestent pareillement le conflit. Voilà une bien jolie alliance !'),
(34, 'Deux Poissons réunis peuvent créer un univers et en être très heureux, ou bien étouffer dans cette relation déconnectée de la réalité. Tout dépendra de la capacité de deux partenaires à s''ancrer, au moins une fois de temps en temps, dans le quotidien, et à accepter de s''ouvrir un peu à son partenaire.'),
(35, 'Le Bélier et la Balance réunis ont toutes les chances de s''apprécier mutuellement et de se tirer vers le haut. En effet, leurs différences les complètent et les ravissent : le Bélier apporte à la Balance la fougue qui lui manque, tandis que cette dernière permet au couple de trouver calme et équilibre. A condition que le Bélier fasse attention à la sensibilité naturellement exacerbée de la Balance, tout devrait fonctionner à merveille !'),
(36, 'L''union entre un Bélier et un Verseau est en général couronnée de succès. Ces deux signes sont faits pour s''entendre car ils partagent la même vision aérienne et joyeuse de la vie. Ils multiplieront donc les projets ensemble et avanceront avec légèreté sur le chemin de l''existence, appréciant pleinement la compagnie de l''autre.'),
(37, 'Cette alliance est dynamique et sentimentale, ces deux signes ont beaucoup à apprendre l’un de l’autre, le Bélier apporte le feu de son tempérament, l’action et le dynamisme et le Poissons sa tendresse. Un duo parfait entre amour et passion.Cependant, la fougue et le côté abrupt du Bélier se heurtent parfois à la douceur et à la rêverie typique du Poisson. Ces deux signes peuvent donc parfois diverger s’ils ne communiquent pas.'),
(38, 'Taureau est séduit par l’art et la manière du Gémeaux  qui le charme par ses mots, son style, sa plume. Il sait parfaitement quoi faire, quoi dire pour l’épingler comme un papillon. Alors que le  Gémeaux tombe sous le charme du Gémeaux sensuel et glamour. Le Taureau ne supporte pas les infidélités de ce charmeur impénitent, qui a besoin d’être rassuré sur le plan de la séduction. Alors s’il apprend qu’il n’est pas le seul à bénéficier de ses mots doux cela risque de tourner vinaigre. En effet,  Le Taureau aspire au calme et à la pérennité de son amour.'),
(39, 'Des étincelles apparaissent quand le Taureau, calme et terre à terre rencontre le Lion dramatique et expressif. Le feu peut réchauffer mais parfois il peut vous brûler tous les deux. L''attirance entre vous provient de vos côtés opposés, le Taureau est physique, sensuel et intéressé à la vie dans l''ici et maintenant alors que le Lion est imaginatif, intuitif et intéressé par les potentiels et l''expression de soi. Le Taureau peut soutenir et donner forme à l''imagination du Lion. Le Lion peut porter l''attention du Taureau sur le monde intérieur. Vous aimez tous les deux la beauté et pouvez partager des intérêts artistiques. En tant qu''équipe créative, c''est une combinaison imbattable, spécialement si vos talents sont complémentaires. '),
(40, 'Il y a une belle complémentarité possible entre un Gémeaux et un Scorpion, même si elle n''est pas des plus évidentes au premier coup d''oeil. Le Gémeaux est du côté solaire, optimiste, joyeux, enthousiaste,  tandis que le Scorpion est du côté obscur , pessimiste, compliqué, torturé. Et pourtant ces deux signes sont faits pour s''apprécier, le Gémeaux offrant légèreté et bonheur au Scorpion, qui de son côté lui apportera complexité et profondeur.'),
(41, 'Le Gémeaux et Le Capricorne sont très différents et pourtant, ils sont faits pour être heureux ensemble. Le Gémeaux va apporter de la légèreté au trop sérieux Capricorne, tandis que ce dernier offrira un peu de pragmatisme à son partenaire qui en manque souvent.'),
(42, 'Ces deux signes sont tous les deux fascinés par les gens, ils ont beaucoup de choses à partager l''un avec l''autre. Il y a des chances pour que cette relation change constamment, étende leur vision du monde et leur compréhension de nombreuses choses.Ils sont tous les deux intelligents, réfléchis. Ils aiment bouger et la routine les ennuie. Ils peuvent ainsi créer un lien mutuellement enrichissant fait d''aventures, de voyages et de nouveaux projets créatifs. '),
(43, 'L''alliance entre un Cancer et une Vierge peut manquer de fantaisie à première vue, pourtant elle est souvent vouée au succès. Ces deux signes discrets se comprennent à merveille. Ils préfèrent l''ombre à la lumière, sont consciencieux et aiment à privilégier leur vie de couple et de famille. Professionnellement rigoureux et travailleurs, ils sont donc sur la même longueur d''onde, quel que soit le domaine de l''existence qui les réunit.'),
(44, 'Passion est le maître mot d''une relation entre un Lion et un Scorpion. Qu''elle soit amoureuse, amicale ou simplement professionnelle. Ces deux signes ne peuvent pas se côtoyer sans se déchirer et se raccommoder sans cesse. Question de tempérament : le Lion aime à rugir, ce que le Scorpion supporte mal. En conséquence de quoi il pique, ce qui fait immédiatement rugir à nouveau le Lion. Et ainsi de suite !'),
(45, 'Les différences existant entre un Lion et un Capricorne sont telles qu''il est difficile de les imaginer ensemble, et pourtant, c''est possible ! Mais uniquement à condition que le respect soit au centre de leur relation. C''est ce qui leur permettra de compenser leurs immenses différences et d''en faire un atout pour leur association. Sans ça, les deux signes s''éviteront soigneusement, chacun symbolisant pour l''autre tout ce qu''il n''aime pas.'),
(46, 'Le Scorpion et la Vierge se fascinent mutuellement, et c''est ce qui constitue en général la base de leur relation. Le premier apprécie la sensibilité exacerbée de la seconde, tandis que cette dernière est captivée par la complexité et la vivacité intellectuelle du premier. Attention, cependant, ces deux signes étant inquiets de nature, à ce qu''ils ne s''entraînent pas dans un pessimisme de mauvais aloi lorsqu''ils sont réunis.'),
(47, 'La relation entre une Balance et un Sagittaire est en général placée sous le signe de la joie de vivre. Ces deux signes étant par nature optimistes, ils apprécient cette qualité chez l''autre et multiplient les projets en commun. Par ailleurs, ils partagent le même goût pour les mondanités et sont tous deux heureux de faire de nouvelles rencontres, ce qui ne les empêche nullement d''apprécier leurs moments en tête-à-tête.'),
(48, 'Il y a du bon et du moins bon dans l''alliance formée par une Balance et un Verseau. Si ces deux signes s''entendent en général à merveille d''un point de vue intellectuel, ils ont du mal à s''accorder émotionnellement. Le Verseau aime la liberté et a du mal à s''engager, ce qui peut frustrer la Balance. De son côté la capacité à papillonner socialement de cette dernière n''incitera pas le Verseau à s''impliquer en profondeur dans leur relation.'),
(49, 'Ces deux signes sont tous les deux des romantiques et préfèrent viser les étoiles plutôt que de s’intéresser au montant de leurs économies. Sur un plan créatif ou sexuel, ils forment un couple plutôt inspiré et ne risquent pas de s’ennuyer l''un avec l''autre. Cependant, la tendance du Scorpion à cacher les choses et ses accès occasionnels de manipulation peuvent entrer en conflit avec la naïveté du Sagittaire et sa tendance à voir les choses en noir et blanc. '),
(50, 'Il y a beaucoup de charme dans une relation entre un Verseau et un Poisson. Ces deux signes ont un imaginaire très fort. Ils apprécient chacun l''univers de l''autre et acceptent de ne pas entièrement le partager. Cette part d''incompréhension fait partie de l''intérêt qu''ils se portent et soutiendra la réussite de leur alliance sur la durée.'),
(51, 'Attention danger ! Si les similarités de caractère de deux Béliers peuvent attirer dans un premier temps - leur côté fonceur, leur enthousiasme, leur impulsivité - ils risquent rapidement de se trouver confrontés l''un à l''autre. Entêtés jusqu''à l''extrême, pas un ne voudra laisser un pouce de terrain dès qu''un différend pointera le bout de son nez. Jusqu''au conflit...'),
(52, 'L''alliance entre un Bélier et un Cancer n''est pas des plus évidentes. Autant le Bélier apprécie le côté maternel du Cancer, autant il peut rapidement se sentir étouffé par toutes les attentions que son partenaire lui porte. \r\nDe son côté ce dernier risque de souffrir de la dureté du Bélier, et lui reprocher son manque d''amour. Il leur faudra beaucoup de patience et de travail pour arriver à un équilibre qui les satisfasse tous les deux.\r\n'),
(53, 'Balance et Taureau ne représentent pas la meilleure association. Il existe en effet de nombreuses incompréhensions entre la première, signe d''Air, légère et parfois un peu superficielle et le second, signe de Terre, pragmatique.  Ils risquent rapidement de se désintéresser l''un de l''autre, et préférer vivre une relation avec quelqu''un dont les convictions sont plus proches des leurs.'),
(54, 'Le Verseau et le Taureau se comprennent mal. Cela les empêche donc souvent de construire une relation stable sur le long terme. Pour le Verseau, la tendance qu''a le Taureau à tout planifier à l''avance s''apparente à une limitation de son espace vital. Tandis que le côté brouillon et enthousiaste du Verseau s''apparente pour le Taureau à de la superficialité.'),
(55, 'Le Gémeaux et le Cancer forment rarement une alliance épanouie sur la durée. Ces deux signes sont trop différents pour réellement devenir complémentaires. Le Cancer est trop terre à terre et en demande affective. Le Gémeaux est quant à lui trop aérien et indépendant. \r\nCes différences risquent de créer une distance entre les deux partenaires, et il y a de fortes chances que celle-ci ne puisse être comblée à terme.\r\n'),
(56, 'La Balance et le Cancer peuvent former un duo réussi si la Balance accepte de mettre la pédale douce sur sa vie sociale afin de se consacrer un peu plus à son compagnon. Et si le Cancer fait des efforts afin de respecter la sensibilité aiguisée de sa partenaire. Cependant ce sont des concessions importantes, et il faudra beaucoup d''amour et de respect mutuel pour que ce couple y arrive sur le long terme.'),
(57, 'Le Cancer et le Verseau souffrent en général d''un problème de communication lorsqu''ils sont réunis. Le Cancer se recroqueville facilement dans sa carapace lorsque sa sensibilité est mise à mal. Ce qui arrive souvent à cause des maladresses et de l''indifférence ponctuelle du Verseau. En outre, tandis que le premier ne rêve que de stabilité, le second a souvent plus de mal à se fixer.'),
(58, 'Le Lion et la Balance sont faits pour s''entendre, pas de doute là dessus. La Balance, toujours hésitante, voit dans l''assurance de son compagnon une merveilleuse épaule sur laquelle s''appuyer tandis que le Lion apprécie pleinement le côté aérien et charmant de la Balance. Le seul domaine où ils peuvent rencontrer de sérieuses difficultés est lié à la façon dont chacun de voit l''amour. Le Lion aime briller aussi souvent que possible et peut parfois oublier qu''une relation demande à ce qu''on reconnaisse les désirs de l''autre. Cela peut mettre la Balance très en colère car pour elle l''équité est très importante.'),
(59, 'Le Lion et le Poisson s''attirent souvent en premier lieu, pour découvrir rapidement qu''ils n''ont pas grand chose en commun, et se détacher l''un de l''autre. Le Poissons est par essence rêveur, détaché des réalités et des contingences matérielles. Tout l''inverse du Lion, flamboyant, matérialiste et peu porté à la rêverie ! Difficile dans ce cas de se comprendre et de s''apprécier l''un l''autre.'),
(60, 'Il n''est pas facile pour une Vierge et un Sagittaire de s''entendre, et encore moins de construire une relation sur la durée. Car leurs différences - les inquiétudes et le pessimisme de la Vierge, les enthousiasmes optimistes du Sagittaire - les empêchent de réellement se comprendre l''un l''autre.'),
(61, 'L''incompréhension est souvent le lot d''une alliance entre une Vierge et un Verseau. Aucun de ces deux signes ne comprend l''autre, et entre le pessimisme de la première et l''optimisme du second c''est l''agacement mutuel qui domine. \r\nLa Vierge est trop terre à terre pour comprendre le côté aérien du Verseau. Ce dernier s''irrite par ailleurs des inquiétudes irraisonnées de la Vierge.\r\n'),
(62, 'Il est difficile pour une Balance et un Capricorne de former une alliance épanouie sur le long terme où chacun y trouve son compte. En effet, le Capricorne est en général rapidement irrité par la légèreté de la Balance qu''il juge superficielle, tandis que cette dernière trouve le Capricorne trop sérieux, et un peu rabat joie.'),
(63, 'La Balance et le Poisson ont beau être très attirés l''un par l''autre, ils éprouvent souvent les plus grandes difficultés à se comprendre. L''univers du Poissons est imperméable à son compagnon qui ne comprend pas son besoin de solitude. De son côté les mondanités de la Balance ennuient son partenaire. Par ailleurs, ils n''ont pas la même vision du couple, ce qui tend à poser problème et à l''un et à l''autre.'),
(64, 'Pour le Sagittaire, signe de feu et le Poisson, signe d''eau, la communication peut être difficile. Le Poisson communique en oblique et sa sensibilité aux atmosphères est plus importante que les explications rationnelles. Le Sagittaire est ouvert, honnête, enthousiaste et peut parfois laisser échapper des choses qui peuvent blesser. Ils doivent faire tous les deux des efforts pour comprendre le langage de l''autre et faire un pas vers l''autre.  Il y a aussi un problème de dépendance-indépendance entre eux. Bien que ni l''un ni l''autre ne soit possessif, le Poissons a besoin de beaucoup d''intimité émotionnelle. Le Sagittaire a besoin de beaucoup de liberté et peut se sentir facilement emprisonné. '),
(65, 'Le coeur fougueux d''un natif du Bélier peut réchauffer et inspirer une native du Taureau qui voit la vie d''une façon impassible et prudente. La stabilité et le calme du Taureau peuvent contenir et calmer l''esprit agité et les rêves parfois mégalos du Bélier. La combinaison peut faire merveille parce que chacun des signes possède des qualités dont l''autre manque. Mais attention à ne pas rester d''une façon obstinée dans des "camps" opposés. Bien que le Bélier aime et s''abreuve de la sérénité et du pragmatisme du Taureau, il peut se sentir facilement étouffé et s''ennuyer si la vie s''enferme dans une routine. Et le Taureau peut se sentir facilement angoissée et menacée par la quête constante de changements et de défis du Bélier. '),
(66, 'Bélier et  Vierge s''entendent rarement sur le long terme. Leurs personnalités sont en effet difficilement compatibles. Le Bélier est trop fougueux et désordonné pour la douce Vierge, tandis que celle-ci agace son compagnon par sa rigidité et son pessimisme naturel. \r\nChacun aura donc tendance à vouloir changer l''autre, sans grand succès naturellement.\r\n'),
(67, 'La nature de ces deux signes rend leur alliance excitante et dangereuse, rien que ça ! Le Bélier et le Scorpion sont faits pour se rencontrer et s''entendre, mais aussi pour s''énerver mutuellement, voire se déchirer. Entiers, butés, ils aiment se disputer puis se réconcilier, persuadés de vivre une relation hors du commun, mais fatigante !'),
(68, 'Le Bélier et le Capricorne ont deux visions radicalement différentes de la vie : le Bélier agit avant de réfléchir, emporté par son enthousiasme. Le Capricorne, signe de Terre, pèse toujours le pour et le contre avant de prendre une décision. Il est le plus pragmatique de tous les signes du zodiaque. Bélier et Capricorne auront donc toujours du mal à se comprendre.'),
(69, 'Il y a peu de chances qu''un Sagittaire et un Taureau arrivent à trouver un mode de vie commun qui leur convienne à tous les deux. Le Taureau ne trouve son équilibre que dans l''organisation et la planification. Avec lui, les choses doivent être carrées, ou n''ont pas lieu d''être. C''est tout l''inverse du Sagittaire, anticonformiste, désorganisé, fourmillant de projets. En général ces deux signes s''apprécient mais parviennent rarement à construire sur la durée.'),
(70, 'Il y a un problème de fond dans la nature de la relation que peuvent entretenir un Sagittaire et un Cancer . C''est la vision même de leur relation qui diffère. Le Cancer aime l''exclusivité, a tendance à materner son partenaire et attend beaucoup en retour. Le Sagittaire, à l''inverse, est épris de liberté et a une vision plutôt analytique de ses émotions. Par ailleurs, le Cancer aime la sécurité, tandis que le Sagittaire n''aime rien tant que vivre de nouvelles aventures.'),
(71, 'Il est possible que le Verseau et le Lion s''accordent sur le long terme. Mais il leur faudra pour cela faire un effort conséquent de part et d''autre pour comprendre le mode de fonctionnement de leur partenaire. Le Verseau devra accepter la part flamboyante du Lion et son narcissisme. Tandis que ce dernier devra comprendre la légèreté et l''esprit d''aventure de son compagnon. C''est à ce prix qu''ils formeront une relation heureuse.'),
(72, 'La Vierge a besoin d''un partenaire solide capable de la rassurer constamment. C''est tout l''inverse de la Balance, signe d''Air léger et mondain, qui n''aime rien tant que socialiser avec des inconnus quitte à délaisser la personne avec qui elle est. La Balance a quant à elle besoin de quelqu''un qui soit capable de prendre les décisions à sa place. Ce qu''est bien incapable de faire la Vierge, trop inquiète pour cela. En résumé ces deux signes n''ont rien à faire ensemble !'),
(73, 'Les personnalités de la Vierge et du Poisson peuvent se compléter à merveille. Mais seulement à partir du moment où chacun des deux partenaires aura compris qu''il ne peut pas saisir le mode de fonctionnement de l''autre !  S''ils acceptent cette part d''inconnu, Vierge et Poissons formeront un couple sentimental, amical ou professionnel des plus réussis, où la notion de respect mutuel sera essentielle.'),
(74, 'La Balance et le Scorpion ont de nombreuses différences, mais c''est ce qui fait qu''ils ont souvent beaucoup à s''apporter l''un l''autre. La Balance est en général fascinée par la complexité souvent tourmentée du Scorpion, tandis que ce dernier trouve dans l''optimisme de son compagnon une vision agréable de la vie. S''ils acceptent le jardin secret de chacun, ils évolueront sereinement tous les deux.'),
(75, 'Il y a souvent de la passion dans l''air lorsqu''un Verseau et un Scorpion se rencontrent. Entre les deux signes le courant passe car les opposés s''attirent, mais sur le long terme la réalité les rattrape souvent. L''optimisme du premier se heurte au pessimisme du second, et la volonté de liberté du Verseau frustre le Scorpion, à la recherche de l''amour absolu. Il leur sera donc difficile de trouver un terrain d''entente qui leur convienne à tous deux.'),
(76, 'Le Sagittaire et le Capricorne ont une vision radicalement différente de l''existence, qui les empêche en général de former une alliance réussie sur le long terme. Le Sagittaire est optimiste, brouillon, toujours prêt à tenter l''aventure. De l''autre se trouve le Capricorne, pessimiste, pragmatique, taciturne et matérialiste, pour qui tout doit être programmé à l''avance pour fonctionner. Les deux, lorsqu''ils se rencontrent, ont donc vraiment peu en commun.'),
(77, 'Ces deux signes s''attirent rarement lorsqu''ils se rencontrent. Si pourtant c''est le cas, leurs multiples différences risquent de venir mettre un terme à leur histoire. Le Capricorne pessimiste, pragmatique et taciturne se heurtera bien vite au Verseau, optimiste, naturellement sociable et rêveur. Ce sera ensuite à qui se lassera de cette histoire le premier...'),
(78, 'Ce n''est pas une bonne alliance que celle d''un Poissons et d''un Capricorne, sauf si ces deux signes font un réel effort pour se comprendre mutuellement, ce qui arrive rarement. En effet, le Poissons n''aime pas le pragmatisme et le matérialisme exacerbé du Capricorne, tandis que ce dernier ne comprend pas l''univers rêveur et détaché des contingences matérielles du Poissons. Ils s''agacent en général plus qu''ils ne s''attirent.'),
(79, 'Le signe du Rat et le signe du Bœuf sont en général sur la même longueur d''onde. Ils partagent le même pragmatisme et la même vision de la vie, axée sur la réalité et la construction lente de projets. Intellectuellement ils bénéficient d''une véritable complicité. Sentimentalement, leur relation manquera peut être un peu de fantaisie, mais en même temps ce n''est pas vraiment dans la personnalité de l''un ou de l''autre.'),
(80, 'Le signe du Rat et le signe du Dragon peuvent former une merveilleuse association, aussi bien affective que professionnelle. En effet ces deux signes sont parfaitement complémentaires. Le dynamisme du Dragon tire le Rat vers le haut, tandis que le côté matériel de ce dernier ancre le Dragon dans la réalité. Ils sont faits pour s''entendre !'),
(81, 'Le signe du Rat et le signe du Singe s''accordent en général à merveille. Les facéties du Singe, loin d''irriter le Rat comme on aurait pu s''y attendre, amusent le Rat au plus haut point. De son côté le Singe se sent rassuré par le côté sérieux et travailleur de son compagnon. Ils passent en général de merveilleux moments ensemble, et peuvent espérer former une belle union.'),
(82, 'Le signe du Bœuf et le signe du Lapin, lorsqu''ils se rencontrent, savent reconnaître au premier coup d''œil l''alter ego qui leur convient. Ils partagent en effet la même vision de la vie, calme et posée, le même besoin de sécurité, les mêmes ambitions simples, la même volonté de confort au quotidien. Leur existence commune peut parfois manquer un peu de fantaisie, mais cela leur convient très bien.'),
(83, 'Il existe une belle complémentarité entre le signe du Bœuf et le signe du Coq. Le premier aime la vitalité et l''exubérance de son partenaire, tandis que le second aime à s''appuyer sur la stabilité et le côté terre à terre du Bœuf. Ils sont tous deux prêts à donner beaucoup s''ils se sentent en confiance, ce qui peut facilement être le cas entre eux. Ils vivront une relation heureuse et épanouie sur le long terme.'),
(84, 'Le Tigre et le Dragon se rejoignent autour d''un dynamisme commun et d''une même vision de la vie. Ils peuvent former un couple optimiste axé sur l''avenir et ses possibilités. Cependant, ils partagent aussi le même égoïsme et narcissisme, ce qui peut poser problème lorsqu''ils rentrent en conflit. Signe du Tigre et signe du Dragon devront mettre beaucoup d''eau dans leur vin s''ils veulent éviter de vivre des crises homériques...'),
(85, 'Une vitalité impressionnante est présente dans un couple formé par un Tigre et un Cheval. Ces deux signes partagent les mêmes caractéristiques : ils sont dynamiques, fonceurs, optimistes et apprécient ces qualités aussi bien chez l''autre que chez eux même. Ensemble, signes du Tigre et signe du Cheval pourront développer de nombreux projets et tout mettre en œuvre pour les réaliser.'),
(86, 'Le Tigre et le Chien s''entendent en général très bien. Le Tigre entraîne le Chien, qui ne demande pas mieux, dans ses aventures, tandis que le signe du Chien offre à son compagnon une loyauté des plus agréables. Par ailleurs, ils ont la même conception de grandes valeurs de la vie et sont tous deux des signes droits et honnêtes.'),
(87, 'Le signe du Lapin et le signe du Serpent sont faits pour se rencontrer et s''aimer. Ils partagent la même vision de l''amour : profond, fidèle, sensible. Le Lapin apporte au Serpent la sérénité dont il a besoin, tandis que ce dernier offre à son compagnon une complexité fascinante. Tant que le Serpent ne complique pas inutilement la relation, tout devrait bien se passer.'),
(88, 'Le signe du Lapin et le signe de la Chèvre partagent la même douceur et la même sensibilité. Ces deux signes sont donc faits pour s''entendre. A condition, toutefois, qu''ils acceptent parfois d''endosser un rôle qui ne leur est pas familier : celui de soutien moral. S''ils y parviennent, ils construiront ensemble une belle relation. Et se découvriront par la même occasion une force de caractère cachée qui leur donnera de l''assurance.'),
(89, 'Un couple formé par un signe du Cochon et un signe du Chat est en général voué à la réussite. Le Cochon est souvent fasciné par son partenaire, sa douceur, sa vivacité intellectuelle, son raffinement. De son côté le Chat découvre avec le Cochon les vertus de l''honnêteté et de la droiture. Ensemble ces deux signes se tirent mutuellement vers le haut et créent une relation tendre et épanouie.'),
(90, 'Il existe en général une réelle admiration entre le signe du Dragon et le signe du Serpent. Le premier apprécie à sa juste valeur la complexité et la vivacité intellectuelle de son compagnon, tandis que le Serpent est fasciné par la flamboyance du Dragon et son aisance en société. A eux deux, ils peuvent former un couple amoureux... Et puissant.'),
(91, 'La fantaisie est souvent au cœur d''une alliance formée par un signe du Dragon et un signe du Singe. Le premier apporte l''enthousiasme et la force, le second l''humour et la légèreté. Intellectuellement ils s''entendent à merveille et s''admirent mutuellement. La droiture et l''honnêteté, essentielles au Dragon, sont parfaitement intégrées par le Singe qui s''emploie à être à la hauteur.'),
(92, 'Il y a une réelle complémentarité possible entre un signe du Serpent et un signe du Coq. Le premier peut apporter une complexité et une vision de la vie fascinantes au second tandis que celui-ci, de par son optimisme peut offrir une bouffée d''air frais à son compagnon. Par ailleurs, le calme du Serpent et la vivacité du Coq ont des chances de se compléter à merveille.'),
(93, 'La compréhension est le maître mot d''une relation entre le signe du Cheval et la Chèvre. S''ils apprécient mutuellement leurs qualités respectives, ils sont surtout capables de comprendre ses défauts et de les pardonner. C''est ce qui fait que leur alliance est si souvent couronnée de succès.'),
(94, 'La complémentarité existant entre le signe du Cheval et le signe du Chien leur permet en général de vivre une très belle relation ensemble. Le Cheval offre sa fougue et son dynamisme, le Chien sa loyauté et sa stabilité. Chacun apporte à l''autre les qualités qui lui font défaut, et ils aboutissent ainsi à un très bel équilibre dans leur histoire.'),
(95, 'Un Cochon, s''il est dans une relation avec une Chèvre, lui apportera une vision optimiste et légère de l''existence, basée sur les nombreux plaisirs du quotidien. Le signe du Cochon sera ravi d''avoir une partenaire qui apprécie les mêmes choses que lui, tandis que de son côté la Chèvre sera heureuse de trouver un compagnon qui lui apporte un nouvel horizon.'),
(96, 'Le signe du Chien et le signe du Cochon ont beaucoup d''atomes crochus, et une conception de la vie relativement similaire. Ils apprécient les plaisirs simples du quotidien, les relations saines, les situations faciles à appréhender. Ils sont tous deux optimistes et fidèles en amitié aussi bien qu''en amour. Ces deux signes sont faits pour s''entendre.'),
(97, 'Le signe du Rat et le signe du Lapin peuvent très bien s''entendre d''un point de vue intellectuel. Ils ont tous deux beaucoup à offrir et peuvent partager de nombreux centres d''intérêt communs. Si, leur alchimie est bien entretenue, cette amitié amoureuse pourra alors devenir une relation passionnée et durable.'),
(98, 'Le signe du Rat et le signe du Serpent pourront parvenir à une alliance heureuse sur le plan affectif - magie de l''amour ! Mais attention, d''un point de vue professionnel, le Rat est travailleur et économe, le Serpent est tout son inverse.'),
(99, 'Le signe du Rat et le signe du Chien ont tout pour construire une union harmonieuse et basée sur le long terme. Certes, il y a peu de chances qu''ils vivent une passion dévorante, mais ce n''est dans la personnalité ni de l''un ni de l''autre. En revanche, ils ont toutes les qualités nécessaires pour fonder un foyer solide et chaleureux.'),
(100, 'Le signe du Bœuf et le signe du Serpent se comprennent souvent très bien dès leur première rencontre, et ont la chance de bénéficier d''une excellente entente intellectuelle. Affectivement c''est un peu plus compliqué. Le Bœuf manque parfois de finesse pour son compagnon, et semble trop pragmatique. Mais ces différences ne sont pas inconciliables, loin de là.'),
(101, 'Le Tigre est fortement attiré par la douceur et la sensibilité du Lapin, tout ce qu’il n’est pas forcément ! Le signe du Lapin offre une telle compassion et un tel réconfort qui amèneront le Tigre à baisser sa garde. Cependant, gare aux éventuels conflits dus au caractère dominant du Tigre qui pourrait blesser son partenaire sans le vouloir.'),
(102, 'Il y a beaucoup de simplicité et de joie dans le cadre d''une relation entre un signe du Tigre et un signe du Cochon. Ces deux signes se comprennent et s''apprécient, admirant chez l''autre les qualités qui leur manquent. Le Cochon aime l''énergie de son compagnon, celui-ci aime la bonhomie et l''optimisme de son partenaire. Ils sont en général très heureux ensemble.'),
(103, 'Le signe du Lapin et le signe du Chien s''entendent en général fort bien lorsqu''ils sont ensemble, ce qui peut surprendre au premier abord. Mais ce qui les différencie les rapproche : le côté loyal et enthousiaste du Chien, lorsqu''il se sent en confiance, comble le Lapin tandis que ce dernier apporte au couple sa douceur et sa sensibilité.'),
(104, 'Lorsque le signe du Lapin et le signe du Cochon mettent au service de leur relation le meilleur d''eux même, cela forme un couple exceptionnel. Le Lapin découvre la droiture du Cochon et son bonheur de vivre, tandis que ce dernier s''émerveille de la douceur, de la sensibilité et de la complexité de son compagnon. Ils ont toutes les chances de vivre ensemble une très belle histoire.'),
(105, 'Il y a une belle complémentarité possible entre un signe du Dragon et un signe du Cochon, mais pour que leur couple fonctionne il faut que les deux signes fassent beaucoup de compromis. Le Dragon doit laisser de la place à son compagnon, et ce dernier doit s''affirmer face à la personnalité écrasante du Dragon.'),
(106, 'Le signe du Serpent peut fasciner le signe de la Chèvre par sa vivacité intellectuelle et sa complexité émotionnelle. De son côté, cette dernière peut amener au Serpent sa douceur et sa sensibilité. Certes leur relation ne sera pas facile tous les jours mais ces deux signes s''apporteront beaucoup d''amour et de respect.'),
(107, 'Alors que le Cheval s''emballe souvent pour un rien, le Coq peut quant à lui agir et réagir de manière excessive. Mais lorsque ces deux signes vont dans la même direction, cela entraîne une vivacité et un enthousiasme de tous les instants. Au point d''être parfois fatigant pour l''entourage. Toutefois, si leurs avis divergent, la confrontation peut être violente et mener au point de non-retour.'),
(108, 'Deux Chèvres réunies sont en général très heureuses ensemble. Leur intelligence et leur douceur communes leur permettent de construire une relation basée sur des sentiments profonds. Par ailleurs, elles comprennent les angoisses de l''autre et mettront tout en œuvre pour leur partenaire. Elles préfèrent toutes les deux privilégier leur vie de couple et leur foyer.'),
(109, 'Une Chèvre et un Singe peuvent s''entendre à merveille, mais il leur faudra pour cela mettre beaucoup d''eau dans leur vin et accepter des concessions importantes. Le signe du Singe devra mettre un bémol à ses taquineries incessantes qui heurtent la sensibilité de la Chèvre, tandis que celle-ci ne devra pas étouffer son partenaire avec ses inquiétudes.'),
(110, 'Le Singe et le Chien peuvent partager un lien très fort, entremêlé d’amitié et d’amour, mais leur complicité pourra être perturbée par les mauvaises taquineries du Singe et le côté casanier et fermé du signe du Chien. Le premier rêve de mondanités, le second plus d''un foyer paisible. S’ils parviennent à faire des concessions, tous deux pourront alors démarrer une vie en commun.'),
(111, 'Le Singe et le Cochon peuvent s''entendre à merveille... ! Tout dépendra de la capacité des deux partenaires à surmonter leurs différences, qui ne sont pas minimes. Le signe du Singe a une personnalité souvent trop complexe pour son compagnon qui se contente des plaisirs simples de la vie. Le Cochon peut quant à lui finir par se lasser du côté railleur du Singe. Mais leur amour l’un pour l’autre les poussera à trouver un équilibre.'),
(112, 'Le signe du Coq et le signe du Cochon ont beaucoup à s''apporter s''ils décident que leur histoire en vaut la peine. Et à condition qu''ils soient tous deux prêts à faire les efforts nécessaires pour qu''elle fonctionne.\r\nLe Premier doit mettre la pédale douce sur ses excès et ses débordements, le second doit se bouger lorsqu''il se laisse aller, pour ne pas risquer de se retrouver à la traîne. A ce prix, ils réussiront à trouver un équilibre.\r\n'),
(113, 'Deux Chiens réunis sont faits pour s''entendre et pour former la plus belle des associations. En effet ils partagent la même conception de la vie et sont en général ravis de rencontrer un partenaire avec les mêmes valeurs : la fidélité, la loyauté et l''honnêteté. Par ailleurs, ils préfèrent de concert privilégier leur vie personnelle par rapport à leur vie sociale.'),
(114, 'Deux Rats ensemble peuvent former un couple heureux, mais il leur sera compliqué de développer une véritable confiance l''un envers l''autre. Ces deux partenaires partagent en effet la même méfiance vis-à vis du monde en général. Par ailleurs, s''ils sont heureux de partager les mêmes qualités, leurs défauts en commun leur poseront beaucoup de problèmes sur le long terme.'),
(115, 'L''alliance entre un signe du Rat et un signe du Tigre est rarement harmonieuse, à cause de leurs conceptions différentes de l''amour. Le Rat a tendance à mettre sa vie sentimentale au centre de ses priorités tandis que le Tigre la place au même plan que ses relations amicales. Ce qui frustre le Rat et étouffe le Tigre... Difficile de tenir comme ça sur le long terme !'),
(116, 'Deux signes du Bœuf réunis sont en général faits pour s''entendre et pour construire une relation solide sur la durée. Certes, cette alliance manquera peut-être de chaleur et de passion, car ces deux caractéristiques sont très éloignées de la personnalité du Bœuf. Mais ils pourront s''appuyer l''un sur l''autre en toutes circonstances et développer leur relation dans la sécurité et le respect mutuels.'),
(117, 'Le signe du Bœuf et le signe du Singe forment une alliance intéressante et parfois couronnée de succès. Il faut pour cela que le Bœuf accepte les taquineries incessantes de son compagnon. Le Singe doit quant à lui comprendre le pragmatisme entêté du Bœuf. Mais si cela arrive, ces deux signes pourront s''apporter beaucoup et vivre une belle relation tous les deux.'),
(118, 'Le signe du Bœuf et le signe du Cochon forment souvent une très belle alliance, et ce sur la durée. Ces deux signes ont de fortes chances d''être très heureux ensemble, et ce malgré l’entêtement de chacun. Le Cochon apporte au Bœuf ce qui lui manque : de la bonhomie, de la joie de vivre et une certaine légèreté. Tandis que celui-ci représente une solidité et une stabilité des plus attirantes pour le Cochon.'),
(119, 'Un couple formé par deux Tigres dégage en général une énergie exceptionnelle. Ils fourmillent de projets en commun et s''amusent follement dans la vie, qu''ils soient tous les deux ou avec d''autres. Ils apprécient la compagnie d''une personne aussi enthousiaste qu''eux. Ils devront cependant faire beaucoup d’efforts de concession, car les conflits s’avèrent très étincelantes pour ces deux signes.'),
(120, 'Le Tigre aime partir à l''aventure sans se poser de questions, quitte à regretter après sa précipitation. Le signe de la Chèvre éprouve à l''inverse beaucoup de difficultés à avancer, bloqué par ses doutes et ses incertitudes. Même si ces deux signes s''apprécient beaucoup, il ne leur sera pas facile de convertir l''autre à leur rythme de vie, ou d''accepter d''abandonner le leur.'),
(121, 'Deux Lapins réunis peuvent représenter une très belle alliance. Ils partagent la même conception de l''existence et profitent au maximum des nombreuses qualités de leur partenaire. Ils sont en revanche tous deux de nature calme, ce qui peut amener leur couple à s''enliser dans une routine dont ils devront se méfier sur le long terme.'),
(122, 'Le couple formé par un signe du Dragon et un signe du Cheval est en général dynamique et enthousiaste. Ensemble, ils fourmillent de projets divers et variés et se poussent mutuellement à les réaliser. Seul bémol, ce sont deux signes très égoïstes qui ont parfois du mal à entendre les demandes de l''autre lorsqu''elles ne concordent pas avec les leurs.'),
(123, 'Le signe du Dragon et le signe du Coq peuvent former un couple harmonieux si les deux signes font un effort commun pour gommer les traits les plus disgracieux de leurs personnalités. C''est ainsi le cas du besoin permanent de briller pour le Dragon, et des excès en tous genres du Coq. Si elles s''accordent là-dessus, ces deux personnalités énergiques peuvent construire de grandes choses ensemble.');
INSERT INTO `description` (`id_description`, `description`) VALUES
(124, 'Le Serpent est le signe chinois le plus complexe. Deux Serpents ensemble forment donc un duo fascinant mais très compliqué à comprendre. Eux même n''y arrivent pas toujours. S''ils sont sur la même longueur d''ondes intellectuellement, en revanche sentimentalement ils risquent de passer de crises en réconciliations, et ce jusqu''à ce que l''un des deux se lasse.'),
(125, 'Le signe du Serpent est souvent trop complexe et angoissé pour le signe du Chien. Tandis que celui-ci a souvent une vision de la vie trop simpliste et des jugements trop tranchés pour le Serpent. Ce dernier a, de plus, souvent tendance à se sentir supérieur intellectuellement, ce qui agace grandement le Chien, à juste titre.'),
(126, 'Il y a de la fougue dans une relation entre deux Chevaux ! Leurs tempéraments enthousiastes et enflammés trouvent un écho direct dans la personnalité de leur partenaire. Ils aiment les mêmes choses et partagent le même enthousiasme dans la vie. Malheureusement, ils partagent aussi le même égoïsme, ce qui pourra poser problème sur le long terme.'),
(127, 'Le signe du Cheval et le signe du Cochon partagent le même amour de la vie et de ses plaisirs. Mais ils divergent sur le rythme à tenir : le Cheval s''emballe pour un rien et va à cent à l''heure, tandis que le Cochon aime contempler le temps qui s''écoule. Cependant, si ces deux signes parviennent à trouver un équilibre à ce sujet, ils formeront un couple bien assorti.'),
(128, 'Une Chèvre et un Chien s''accordent rarement, aussi bien sentimentalement que professionnellement. Ils ont tous deux une vision différente de la vie : la Chèvre est philosophe, calme et ouverte sur le monde, malgré sa timidité. Le signe du Chien peut être têtu et fermé, avec des jugements à l''emporte-pièce qui ne lui font pas honneur. Ils ne se comprennent pas et ne s''en donnent pas les moyens.'),
(129, 'Le Singe et le Coq ont peu de chances de s''épanouir ensemble sur le long terme. Le signe du Singe risque en effet de se lasser bien vite des excès en tous genres de son compagnon. Tandis que le signe du Coq goûtera peu les facéties et les moqueries du Singe. Ils se sépareront sans doute lorsque l''un des deux ira trop loin, une fois de trop.'),
(130, 'Le signe du Rat et la signe de la Chèvre forment rarement une alliance heureuse car leurs deux caractères s''accordent mal et sont plus dissemblables que complémentaires. La nature complexe et difficile du Rat ennuie la Chèvre, douce et calme. De son côté celle-ci manque d''intérêt pour le Rat qui a tendance à la regarder de haut.'),
(131, 'Le signe du Rat et le signe du Coq n''ont pas grand-chose à faire ensemble et ne s''apprécient que rarement. En effet le Rat trouve souvent le Coq vulgaire, tandis que ce dernier s''irrite des manières policées et parfois hypocrites de son vis à vis. En résumé, ces deux signes ont plus de chance de s''énerver mutuellement que de s''apprivoiser...'),
(132, 'Le signe du Bœuf et le signe du Cheval réunis souffrent souvent de leurs différences de caractères et arrivent rarement à les surmonter. Le calme du Bœuf, tout comme son pragmatisme s''opposent en effet à la fougue du Cheval, à son désordonné et à ses rêveries sans fin. En bref, quasiment rien ne les réunit, et tout les sépare...'),
(133, 'Le signe de la Chèvre est souvent trop sanguine pour le signe du Bœuf, qui comprend mal les élans passionnés de sa partenaire. De son côté cette dernière s''irrite du pragmatisme terre à terre du Bœuf et lui reproche de manquer d''imagination. Cependant, si les deux signes ont envie que leur histoire fonctionne, ils réussiront à mettre de côté leurs différends et formeront dans ce cas une alliance des plus réussies.'),
(134, 'Le signe du Bœuf et le signe du Chien ont trop de défauts en commun pour que leur alliance soit une réussite sur la durée. Ils partagent le même entêtement, le même refus d''admettre qu''ils ont tort, les mêmes réactions lorsqu''ils se sentent attaqués, ce qui donne des conflits homériques aux conséquences graves. Par ailleurs, ils manquent tous deux d''ouverture d''esprit, ce qui risque de restreindre peu à peu leur univers commun.'),
(135, 'Le Tigre et le Serpent ne sont pas faits pour être ensemble. Et s''ils décident quand même de construire une histoire, il y a peu de chances que celle-ci fonctionne sur le long terme. Remuant, dynamique, optimiste, le signe du Tigre n''a que peu d''atomes crochus avec le Serpent, taciturne, complexe, manipulateur, et souvent pessimiste...'),
(136, 'Le Tigre et le signe du Coq sont deux signes excessifs par nature. Ils auront des difficultés, s''ils sont réunis à ne pas chercher à prendre l''ascendant l''un sur l''autre de manière éclatante. Cela donnera une relation passionnée et souvent conflictuelle qui pourra fonctionner mais pourra lasser l''un ou l''autre sur le long terme.'),
(137, 'Le signe du Lapin et le signe du Dragon sont deux signes très différents. Mais ce sont justement leurs différences qui peuvent les rendre complémentaires. Le Lapin aimera chez son compagnon sa vivacité, son enthousiasme et son besoin de briller en société. Tandis que le Dragon appréciera le calme et la sensibilité du Lapin à leur juste valeur.'),
(138, 'Le signe du Lapin et le signe du Singe, lorsqu''ils sont en couple, vivent en général une relation complexe et passionnée. Ils apprécient chacun les qualités de l''autre. Le Lapin aime l''insouciance joyeuse du Singe, tandis que celui-ci trouve avec le Lapin stabilité et douceur qui lui manquent. Mais ils se heurtent à deux visions de l''amour différentes. Le Lapin cherche un partenaire sûr et solide, le Singe un compagnon avec qui s''amuser.'),
(139, 'Deux Dragons ensemble représentent le couple le plus puissant de tout le zodiaque chinois. Ces deux personnalités ensemble démultiplient leur vitalité, leur dynamisme, leur flamboyance, leurs projets, jusqu''à ce qu''on ne voie plus qu''eux ! Seul problème, chacun veut être sur le devant de la scène. Or il n''y a pas toujours de place pour deux...'),
(140, 'Une étincelle peut rapidement jaillir entre un signe du Dragon et un signe de la Chèvre. Ces deux signes partagent une haute vision de l''amour. Ces deux signes possèdent énormément de différences. La Chèvre admire le Dragon et son appétit de vivre. De son côté, celui-ci apprécie la sensibilité et la douceur de son partenaire. Mais à la longue, tous deux se lasseront des changements d’humeur de chacun, et ne se focaliseront plus que sur les défauts de leur partenaire.'),
(141, 'Il est rare qu''un signe du Serpent et un signe du Cheval s''entendent à merveille. Ils ont tous deux une manière d''aborder la vie radicalement différente. Le Cheval ne pense pas il agit, à l''opposé du Serpent qui avance parfois, mais seulement après tergiversé de nombreuses fois. Par ailleurs le Cheval est franc comme l''or, ce qui n''est pas toujours le cas de son compagnon.'),
(142, 'Une Chèvre et un Coq ont peu de chance de s''apprécier longtemps. Le signe du Coq, peu diplomate, a toutes les chances de heurter bien vite la sensibilité de la Chèvre. Par ailleurs il risque de s''agacer tout aussi rapidement des angoisses de sa partenaire, et refuser de leur accorder l''attention qu''elles méritent. La Chèvre se sentira alors blessée et se renfermera sur elle-même.'),
(143, 'Il y a de la joie et de la fantaisie dans un couple formé par deux Singes. Ils se retrouvent autour d''un sens de l''humour de tous les instants et d''une même vision de la vie, légère et facétieuse. Il est clair qu''ils ne s''ennuieront jamais ensemble et riront beaucoup au quotidien, mais ils devront faire attention à ne jamais faire de surenchère de moqueries, elles finiraient par atteindre et blesser l''un des deux.'),
(144, 'Le signe du Coq et le signe du Chien ne sont pas faits pour vieillir ensemble. Le premier est trop excessif, autocentré, abrupt ; le second est taciturne, méfiant, peu ouvert à la nouveauté et aux surprises de la vie. Ces deux signes ont peu en commun et s''intéressent rarement l''un l''autre, dans le meilleur des cas ils préfèrent s''ignorer.'),
(145, 'On dit "copains comme cochon" lorsque deux êtres s''entendent à merveille. C''est particulièrement vrai lorsque deux personnes du signe chinois du Cochon se rencontrent ! Ils partagent la même vision hédoniste de la vie et sont en général ravis d''avoir trouvé un partenaire qui soit sur la même longueur d''ondes qu''eux. Ils doivent simplement faire attention à ne pas trop se laisser aller lorsqu''ils sont réunis. Généralement, ces deux signes ne sont faits que pour rester amis.'),
(146, 'Le signe du Rat et le signe du Cheval ont une forte capacité à générer chez l''autre... de l''agacement. Le côté sérieux et terre à terre du Rat irrite en effet le Cheval. Tandis que les manières abruptes et désinvoltes de ce dernier insupportent le Rat. En revanche, s''ils partagent le même objectif professionnel, ils peuvent former une très belle alliance dans ce domaine.'),
(147, 'Il est rare que le signe du Bœuf et le signe du Tigre réussissent à se comprendre et à s''apprécier longtemps. En général ils s''agacent bien vite : le Bœuf est trop statique par rapport au Tigre, trop remuant. Il est aussi trop terre à terre et pragmatique, tandis que le Tigre est désordonné et aventurier. Ils ne comprennent pas le mode de vie de l''autre et en général, ne s''y intéressent pas, préférant d''autres compagnons plus compatibles.'),
(148, 'Les chances que le signe du Dragon et le signe du Bœuf forment un couple épanoui sont assez faibles sur le long terme, car leurs différences les éloignent plus qu''elles ne les rapprochent. Le Dragon est trop expansif et flamboyant pour le Bœuf. Ce dernier ennuie en outre son compagnon par son côté routinier et prévoyant. Chacun risque rapidement de se désintéresser de l''autre.'),
(149, 'Le signe du Singe admire chez son partenaire sa vitalité et son enthousiasme, tandis que ce dernier aime la spiritualité de son compagnon. Ils ont de fortes chances de beaucoup s''amuser ensemble, et bénéficient en outre d''une très belle complicité intellectuelle. Un Tigre et un Singe partageront beaucoup en commun, mais il est rare que leur relation dépasse le stade de l’amitié.'),
(150, 'Il est difficile pour un signe du Lapin et un signe du Cheval de se combler mutuellement sur le long terme. Ils ont chacun des caractères difficilement compatibles : le Lapin est trop casanier pour son compagnon, tandis que les habitudes du Cheval irritent souvent son partenaire. Par ailleurs le Lapin est un signe extrêmement sensible, et il peut facilement être heurté par les manières brusques de son compagnon.'),
(151, 'Le signe du Coq ne dispose en général pas de la douceur et de la diplomatie nécessaire pour apprivoiser le Lapin. De son côté, ce dernier est incapable d''apporter à son partenaire l''enthousiasme et les excès dont il est friand. Ces deux signes forment donc rarement une alliance des plus réussies sur le long terme.'),
(152, 'Il y a peu de chances qu''un signe du Dragon et un signe du Chien forment un couple épanoui, leurs différences sont trop importantes. Le Dragon, ouvert et généreux, se heurte à la fermeture d''esprit du Chien et vit très mal lorsque celui-ci contredit son point de vue. Et lorsqu''ils sont en conflit la situation peut facilement dégénérer, aucun des deux n''acceptant de céder un pouce de terrain.'),
(153, 'Le signe du Serpent et le signe du Singe n''ont rien en commun, pourtant à deux, ils peuvent former un couple harmonieux. Mais il faut pour cela qu''ils arrivent à surmonter leurs différences : que le Singe arrête d''asticoter sans cesse son compagnon, et que ce dernier limite ses cogitations à n''en plus finir. S''ils y arrivent, leur alliance sera couronnée de succès.'),
(154, 'Le signe du Serpent et le signe du Cochon pourraient s''apporter beaucoup. Et pourtant, cela arrive rarement. Le Serpent pourrait offrir une certaine complexité intellectuelle à son compagnon qui de son côté pourrait lui apporter optimisme et appréciation des plaisirs de la vie. Cependant en général, le Serpent n''amène que sa supériorité et son pessimisme, ce qui fait immédiatement fuir le Cochon.'),
(155, 'Le Cheval et le Singe peuvent s’entendre parfaitement… dans le cadre d’une relation amicale ! Effectivement, ces deux signes aiment partager ensemble des moments simples, cependant il sera difficile pour le Cheval, trop individualiste, d’accepter de suivre le Singe qui risque d’étouffer son partenaire avec ses mondanités.'),
(156, 'Deux Coqs ensemble peuvent accomplir de grandes choses quand ils s''allient, en particulier d''un point de vue professionnel. Mais leur association amoureuse est rarement couronnée de succès. Ils sont tous deux trop égoïstes et manquent trop de diplomatie pour combler un partenaire à leur image. Leurs excès ont tendance à se multiplier lorsqu''ils sont ensemble.');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id_user` bigint(100) NOT NULL,
  `user_bday` date NOT NULL,
  `date_creation` datetime NOT NULL,
  `last_connection` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
